import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/store.dart';

Future<void> createStore(Store store) async {
  try {
    await FirebaseFirestore.instance.collection('stores').add({
      'name': store.name,
      'address': store.address,
      'latitude': store.latitude,
      'longitude': store.longitude,
      'blurb': store.blurb,
      'phoneNumber': store.phoneNumber,
      'imageUrl': store.imageUrl,
    });
  } catch (e) {
    print('Error creating store: $e');
    rethrow;
  }
}

final List<Store> sampleStores = [
  Store(
    storeId: '',
    name: 'Tita’s Sari-Sari Store',
    address: '123 Barangay St, Quezon City, Metro Manila',
    latitude: 14.6760,
    longitude: 121.0437,
    blurb: 'Your friendly neighborhood store with snacks, canned goods, and more!',
    phoneNumber: '+63 912 345 6789',
    imageUrl: 'https://example.com/images/store1.jpg',
  ),
  Store(
    storeId: '',
    name: 'Aling Nena’s Fresh Produce',
    address: '456 Palengke Rd, Makati City',
    latitude: 14.5547,
    longitude: 121.0244,
    blurb: 'Fresh vegetables and fruits daily. Local and organic options available.',
    phoneNumber: '+63 922 876 5432',
    imageUrl: 'https://example.com/images/store2.jpg',
  ),
  Store(
    storeId: '',
    name: 'Manong Pedro’s Eatery',
    address: '789 Tindahan Ave, Pasig City',
    latitude: 14.5764,
    longitude: 121.0851,
    blurb: 'Lutong bahay meals perfect for lunch breaks and take-outs.',
    phoneNumber: '+63 933 112 2334',
    imageUrl: 'https://example.com/images/store3.jpg',
  ),
  Store(
    storeId: '',
    name: 'Lola’s Homemade Goodies',
    address: '321 Kanto St, Marikina City',
    latitude: 14.6507,
    longitude: 121.1029,
    blurb: 'Kakanin, puto, kutsinta, and other sweet delicacies made with love.',
    phoneNumber: '+63 945 667 7890',
    imageUrl: 'https://example.com/images/store4.jpg',
  ),
  Store(
    storeId: '',
    name: 'Juan’s Repair Hub',
    address: '555 Ayos St, Caloocan City',
    latitude: 14.6581,
    longitude: 120.9900,
    blurb: 'All-in-one electronics and appliance repair services.',
    phoneNumber: '+63 918 555 2211',
    imageUrl: 'https://example.com/images/store5.jpg',
  ),
  Store(
    storeId: '',
    name: 'Kape’t Pandesal Café',
    address: '22 Aroma Lane, Taguig City',
    latitude: 14.5243,
    longitude: 121.0792,
    blurb: 'Cozy coffee shop with classic Pinoy breakfast favorites.',
    phoneNumber: '+63 917 334 4455',
    imageUrl: 'https://example.com/images/store6.jpg',
  ),
  Store(
    storeId: '',
    name: 'Suki Meat Shop',
    address: '123 Paluto St, Mandaluyong City',
    latitude: 14.5794,
    longitude: 121.0359,
    blurb: 'Affordable and fresh meat cuts daily.',
    phoneNumber: '+63 921 567 8890',
    imageUrl: 'https://example.com/images/store7.jpg',
  ),
  Store(
    storeId: '',
    name: 'Barangay Barbershop',
    address: '101 Gupit Ave, Valenzuela City',
    latitude: 14.7000,
    longitude: 120.9500,
    blurb: 'Classic haircuts and grooming with a smile.',
    phoneNumber: '+63 923 778 3399',
    imageUrl: 'https://example.com/images/store8.jpg',
  ),
  Store(
    storeId: '',
    name: 'Baker’s Bites',
    address: '44 Tasty Rd, Antipolo City',
    latitude: 14.5844,
    longitude: 121.1761,
    blurb: 'Artisan breads and pastries fresh out of the oven.',
    phoneNumber: '+63 926 543 2121',
    imageUrl: 'https://example.com/images/store9.jpg',
  ),
  Store(
    storeId: '',
    name: 'Piso WiFi Corner',
    address: 'Corner Lot, San Juan City',
    latitude: 14.6042,
    longitude: 121.0317,
    blurb: 'Fast and reliable piso WiFi service for students and workers.',
    phoneNumber: '+63 934 123 4567',
    imageUrl: 'https://example.com/images/store10.jpg',
  ),
  Store(
    storeId: '',
    name: 'Nanay’s Ukay-Ukay',
    address: 'Market Zone, Las Piñas City',
    latitude: 14.4500,
    longitude: 120.9833,
    blurb: 'Preloved fashion at super affordable prices.',
    phoneNumber: '+63 935 789 3456',
    imageUrl: 'https://example.com/images/store11.jpg',
  ),
  Store(
    storeId: '',
    name: 'Botika ni Kuya',
    address: 'Health Lane, Parañaque City',
    latitude: 14.4793,
    longitude: 121.0198,
    blurb: 'Affordable generic medicines and health products.',
    phoneNumber: '+63 936 111 9876',
    imageUrl: 'https://example.com/images/store12.jpg',
  ),
  Store(
    storeId: '',
    name: 'Dangwa Flower Kiosk',
    address: '123 Bloom St, Sampaloc, Manila',
    latitude: 14.6135,
    longitude: 120.9886,
    blurb: 'Colorful fresh flower arrangements daily.',
    phoneNumber: '+63 938 111 4567',
    imageUrl: 'https://example.com/images/store13.jpg',
  ),
  Store(
    storeId: '',
    name: 'Ate Joy’s School Supplies',
    address: 'Katipunan Ave, Quezon City',
    latitude: 14.6392,
    longitude: 121.0776,
    blurb: 'All you need for back to school and daily projects.',
    phoneNumber: '+63 937 789 8888',
    imageUrl: 'https://example.com/images/store14.jpg',
  ),
  Store(
    storeId: '',
    name: 'Barato Grocery',
    address: 'Discount Lane, Navotas City',
    latitude: 14.6667,
    longitude: 120.9367,
    blurb: 'Daily essentials at sulit prices!',
    phoneNumber: '+63 939 456 9090',
    imageUrl: 'https://example.com/images/store15.jpg',
  ),
  Store(
    storeId: '',
    name: 'Handy Hardware Depot',
    address: 'Toolbox St, Muntinlupa City',
    latitude: 14.3811,
    longitude: 121.0444,
    blurb: 'From hammers to hinges — we’ve got it!',
    phoneNumber: '+63 930 303 1010',
    imageUrl: 'https://example.com/images/store16.jpg',
  ),
  Store(
    storeId: '',
    name: 'Pawfect Pet Shop',
    address: 'Petville, Malabon City',
    latitude: 14.6686,
    longitude: 120.9617,
    blurb: 'Treats, toys, and love for your furry friends.',
    phoneNumber: '+63 931 121 1221',
    imageUrl: 'https://example.com/images/store17.jpg',
  ),
  Store(
    storeId: '',
    name: 'Rice Dealer Corner',
    address: 'Bigas Ave, Cavite City',
    latitude: 14.4791,
    longitude: 120.8963,
    blurb: 'Affordable sacks of rice for every family.',
    phoneNumber: '+63 932 333 4444',
    imageUrl: 'https://example.com/images/store18.jpg',
  ),
  Store(
    storeId: '',
    name: 'Gadget Hub PH',
    address: 'Digital Plaza, Laguna',
    latitude: 14.1860,
    longitude: 121.5654,
    blurb: 'Latest tech and mobile accessories.',
    phoneNumber: '+63 933 555 6666',
    imageUrl: 'https://example.com/images/store19.jpg',
  ),
  Store(
    storeId: '',
    name: 'Tambayan Food House',
    address: 'Barkadahan St, Rizal',
    latitude: 14.5204,
    longitude: 121.1264,
    blurb: 'Best barkada meals and milk tea combos!',
    phoneNumber: '+63 934 444 7777',
    imageUrl: 'https://example.com/images/store20.jpg',
  ),
];

Future<void> seedStores() async {
  for (final store in sampleStores) {
    await createStore(store);
  }
}
