// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY-2R0EX1vY1T5UTSJSrVLV-whQSmjU1w',
    appId: '1:342791532648:web:85714f4e0b1c238cb6cbdd',
    messagingSenderId: '342791532648',
    projectId: 'tindahanap',
    authDomain: 'tindahanap.firebaseapp.com',
    storageBucket: 'tindahanap.firebasestorage.app',
    measurementId: 'G-DST5DB9KXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwRDPqE7S1_tlRhfWTiv9Ni3_AUB3sbfU',
    appId: '1:342791532648:android:adeeb2029645ffeab6cbdd',
    messagingSenderId: '342791532648',
    projectId: 'tindahanap',
    storageBucket: 'tindahanap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4JWsgGpTBtvcyH0CUmx5QLN85AhLiBBE',
    appId: '1:342791532648:ios:6d64724f6b6d56a8b6cbdd',
    messagingSenderId: '342791532648',
    projectId: 'tindahanap',
    storageBucket: 'tindahanap.firebasestorage.app',
    iosBundleId: 'com.example.tindahanap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4JWsgGpTBtvcyH0CUmx5QLN85AhLiBBE',
    appId: '1:342791532648:ios:6d64724f6b6d56a8b6cbdd',
    messagingSenderId: '342791532648',
    projectId: 'tindahanap',
    storageBucket: 'tindahanap.firebasestorage.app',
    iosBundleId: 'com.example.tindahanap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY-2R0EX1vY1T5UTSJSrVLV-whQSmjU1w',
    appId: '1:342791532648:web:7a31fe9b4d85a04db6cbdd',
    messagingSenderId: '342791532648',
    projectId: 'tindahanap',
    authDomain: 'tindahanap.firebaseapp.com',
    storageBucket: 'tindahanap.firebasestorage.app',
    measurementId: 'G-207EHQV35R',
  );
}
