final List<Map<String, dynamic>> sampleProducts = [
  {"name": "Motor Oil", "price": 250},
  {"name": "Snacks", "price": 30},
  {"name": "Soft Drinks", "price": 20},
  {"name": "Windshield Wiper", "price": 120},
  {"name": "Car Freshener", "price": 45},
  {"name": "Bottled Water", "price": 15},
  {"name": "Energy Drink", "price": 50},
  {"name": "Cigarettes", "price": 150},
  {"name": "Ice Cream", "price": 40},
  {"name": "Instant Noodles", "price": 25},
  {"name": "Cookies", "price": 35},
  {"name": "Chips", "price": 28},
  {"name": "Gasoline Additive", "price": 180},
  {"name": "Mobile Load Card", "price": 100},
  {"name": "Flashlight", "price": 95},
  {"name": "Umbrella", "price": 220},
  {"name": "First Aid Kit", "price": 500},
  {"name": "Toiletries Kit", "price": 80},
  {"name": "Hand Sanitizer", "price": 60},
  {"name": "Face Mask (Pack)", "price": 35},
];
